-- Doctors table schema for Supabase
create table public.doctors (
  id bigint generated by default as identity primary key,
  name text not null,
  title text not null,
  image text not null,
  image_alt text not null,
  schedule text,
  specialty text,
  specialty_icon text,
  available_today boolean default false,
  icon text,
  icon_position text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Enable Row Level Security (RLS)
alter table public.doctors enable row level security;

-- Create policy to allow public read access
create policy "Doctors are viewable by everyone"
  on public.doctors for select
  using (true);

-- Create policy to allow authenticated users to insert
create policy "Doctors can be inserted by authenticated users"
  on public.doctors for insert
  with check (auth.role() = 'authenticated');

-- Create policy to allow authenticated users to update
create policy "Doctors can be updated by authenticated users"
  on public.doctors for update
  using (auth.role() = 'authenticated');

-- Create policy to allow authenticated users to delete
create policy "Doctors can be deleted by authenticated users"
  on public.doctors for delete
  using (auth.role() = 'authenticated');